
[redis]
REDIS_SET_PREFIX = "REDIS_SET_"
REDIS_SORTED_SET_PREFIX = "REDIS_SORTED_SET_"
REDIS_LIST_SEPARATOR = "#"
REDIS_SORTED_SET_SCORE_LEN = 32
REDIS_FIELD_SEPARATOR = "$"
REDIS_FIELD_PREFIX = "REDIS_FIELD_"
REDIS_HASH_VALUE_PREFFIX = "REDIS_HASH_VALUE_"
REDIS_EXPIRE_HEADER = "REDIS_EXPIRE_"

[bloom_filter]
BLOOM_FILTER_EXPECTED_ERROR_RATE = 0.10000000000000001
BLOOM_FILTER_EXPECTED_SIZE = 65536

[lsm]
cache = {LSM_BLOCK_CACHE_K=8,LSM_BLOCK_CACHE_CAPACITY=1024}

[lsm.core]
LSM_SST_LEVEL_RATIO = 4
LSM_BLOCK_SIZE = 32768
LSM_PER_MEM_SIZE_LIMIT = 4194304
LSM_TOL_MEM_SIZE_LIMIT = 67108864


